stages:
  - test

test_backend:
  stage: test
  when: manual
  image: python:3.12
  script:
    - cd backend
    - pip install ".[dev]"  
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/..
    - pytest tests/
